name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ghcr.io/lawrence-d-lee/text_generator:latest
           docker run ghcr.io/lawrence-d-lee/text_generator:latest
           docker push ghcr.io/lawrence-d-lee/text_generator:latest
